### ISSUE TITLE
Afficher les activités des utilisateurs

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#448]
**Description**
Sur la page d'un utilisateur, afficher la liste de ses dernières activités.
Par exemple "Sébastien a modifié le projet SemApps", avec un lien vers la page du projet.

**Issues liées**
- [x] Mettre en cache les activités ActivityPub #311
- [x] Gérer la pagination sur les collections ActivityPub #310
- [x] Rendre plus flexible le choix des containers ActivityPub #491
- [x] Générer une activité ActivityPub à chaque modifications du serveur LDP #131
- [ ] Créer un générateur de résumés ActivityPub #446
- [ ] Créer un package frontend pour l'affichage des données ActivityPub #447

**Estimation du temps de travail en JH**
- @srosset81 et @simonLouvet : 11 JH, en incluant les 3 JH qui ont été nécessaires pour les 3 premières issues
