### ISSUE TITLE
Pouvoir lier deux instances SemApps

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#451]
**Description**
Pouvoir lier une ressource d'une instance SemApps avec une resource d'une autre instance.

**Support de réflexions** 
https://docs.google.com/presentation/d/1zqt2n9hgnwlwAR42Zz24pFu7nckDPz_RPhxbEHZhQS8/edit

**Frontend**
- [x] #794  - **4 JH**
  - [x] #686 - _(compris dans issue précédente)_
  - [ ] #855 - **1 JH** _(option en plus des 4 JH)_
  - [x] #845 - **2 JH** _(option en plus des 4 JH)_
- [x] #353 - **3 JH**
- [x] #354 - **1 JH**
- [x] #945 - **1 JH**

**Middleware**
- [x] #517 - **1 JH**
- [x] #849 - **3 JH**
- [x] #850 - **1 JH**
- [x] #698 - **2 JH**
  - [ ] Passer par ActivityPub pour la synchronisation des données publiques - **3 JH** _(option)_
- [x] #771 - **0.5 JH**
- [x] #652 - **2 JH** _(option)_

**Comptes-rendus de réunions**
- https://pad.lescommuns.org/3McjRck3Rz2HID6XvcqwBw
- https://pad.lescommuns.org/WkEjbl5oSiCyrKwI1xZmxQ
- https://pad.lescommuns.org/kjsahFvmScyI3kVKEIEXwQ
- https://pad.lescommuns.org/jwkmyoEuSFaNSWnpr3KPNg
- https://pad.lescommuns.org/iA0_DuPjTHuVBRKWDBI68g
- https://pad.lescommuns.org/frkOg6DXS-qTiWpPtfH7Iw?view
- https://forums.assemblee-virtuelle.org/t/suivi-du-chantier-interoperabilite-semapps/246

**Estimation du temps de travail en JH** (optimiste)
- Temps de spec déjà passé (et d'exploration, recherche):
  - @srosset81 : 4 JH (+ 3 JH bénévole)
  - @nikoPLP : 2 JH
- Temps d'implémentation restant:
  - sans les options: 16.5 JH
  - avec toutes les options: 24.5 JH

**Comment by srosset81** [comment]
Dans les discussions avec @simonLouvet, nous avions parlé de gérer la recherche par la requête SPARQL fédérée dans un premier temps, puis de voir pour une solution via Elasticsearch. Personnellement j'ai de la peine à croire à la requête SPARQL fédérée, et je ne suis pas sûr que ce soit si simple à implémenter. Ce serait une option intéressante à proposer, mais est-ce que cela vaut la peine de le faire tout de suite ?

**Comment by srosset81** [comment]
> Dans les discussions avec @simonLouvet, nous avions parlé de gérer la recherche par la requête SPARQL fédérée dans un premier temps, puis de voir pour une solution via Elasticsearch. Personnellement j'ai de la peine à croire à la requête SPARQL fédérée, et je ne suis pas sûr que ce soit si simple à implémenter. Ce serait une option intéressante à proposer, mais est-ce que cela vaut la peine de le faire tout de suite ?

Suite à la discussion de ce jour, nous avons réalisé qu'il y avait une confusion entre une vraie requête SPARQL fédérée (qui est compliquée) et un simple appel à de multiples endpoints SPARQL. Nous avons donc séparé en deux issues: #461 et #450. Et du coup Elasticsearch devient une option, qu'on aimerait bien pousser s'il y a le budget, car cela améliorera nettement les performances.

**Comment by srosset81** [comment]
@simonLouvet @bouviermullerp J'ai ajouté l'issue #652 à ce chantier et j'ai augmenté de 2 jours le temps nécessaire pour son implémentation.

**Comment by bouviermullerp** [comment]
J'ajoute un petit commentaire, qui me vient à l'esprit suite à discussion avec Thomas des 100 lieux nourriciers. Comme on commence à avoir plusieurs plateformes en prod, peut être un point de vigilance à faciliter les migrations des instances d'une version à une autre. Je pose ça là, je pense que vous l'avez déjà bien en tête, mais au cas ou :)

**Comment by srosset81** [comment]
> J'ajoute un petit commentaire, qui me vient à l'esprit suite à discussion avec Thomas des 100 lieux nourriciers. Comme on commence à avoir plusieurs plateformes en prod, peut être un point de vigilance à faciliter les migrations des instances d'une version à une autre. Je pose ça là, je pense que vous l'avez déjà bien en tête, mais au cas ou :)

On s'est amélioré de ce côté avec la description des changements à chaque nouvelle release:
https://github.com/assemblee-virtuelle/semapps/releases
C'est seulement quand on passe de 0.X à 0.Y qu'il y a des "breaking changes" qui doivent être pris en compte (et ils sont décrit)

**Comment by srosset81** [comment]
Enfin ! ;-)
