### ISSUE TITLE
Intégrer la nouvelle version de PAIR

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#452]
**Issues**
- [x] Gérer owl:SymmetricProperty #456
- [x] Créer une instance pour l'UTT avec la nouvelle ontologie #458 
- [x] Migrer Archipel vers la nouvelle ontologie #469 
- [x] Réfléchir aux classes et aux relations qu'on veut intégrer à Archipel

**Comment by srosset81** [comment]
Pour que @J9rem puisse travailler sereinement sur l'instance Archipel en janvier, il me semble qu'il serait important qu'un travail de spec soit fait au préalable: qu'est-ce qu'on veut voir comme type de données, comment est-ce qu'on les lie entre elles ?

Est-ce que quelqu'un pourrait porter ce chantier ?

Ping @bouviermullerp @GuillaumeAV

**Comment by bouviermullerp** [comment]
++ très favorable à ce travail préalable @srosset81 - une approche par les usages me semble vraiment appropriée. Il me semble que @GuillaumeAV est la meilleure personne pour ce chantier, ravi de l'épauler au besoin.
C'est un joli challenge car - d'après ce que je comprends - l'ontologie PAIR est une conception de Guillaume qui le modélise à la fois via ces observations, mais aussi via ses rêves et ses envies. 
Une des manières de faire serait de prendre l'ontologie "telle qu'elle", comme elle est modélisée dans l'esprit de Guillaume, puis de la faire évoluée.

Lors de la V1 de SemApps, je me suis senti un peu frustré, car à la fin de sa vie, j'avais l'impression que c'était un joyeux fourre tout, dans lequel on intégrait de plus en plus de concepts, ce qui me rendait la navigation un peu compliquée.

**Comment by srosset81** [comment]
Pour finir je me suis occupé moi-même de la migration vers la nouvelle version de l'ontologie.
Je n'ai rien ajouté de nouveau, si ce n'est les documents, que j'avais déjà défini dans un autre projet.
Il reste donc la question de ce qu'on veut intégrer de la nouvelle ontologie dans archipel. Je pense que @J9rem pourra s'occuper de l'intégration une fois le plan établi.
Je propose donc de laisser ce chantier ouvert, je l'ai mis à jour en concordance.

**Comment by GuillaumeAV** [comment]
C'est super Seb ! Merci beaucoup  Hâte de pouvoir contribuer sur ce sujet !
