### ISSUE TITLE
Mettre en  place les droits ACL

### ISSUE THREAD

**Issue by bouviermullerp** [assemblee-virtuelle/semapps#52]
**Description**
Customiser Fuseki pour qu'il prenne en compte les droits ACL en lecture et en écriture.
Créer un service Moleculer qui s'occupe d'ajouter et supprimer les droits, en fonction des régles métiers.

**Fuseki**
- [x] Prendre en compte les droits ACL en lecture et en écriture assemblee-virtuelle/semapps#569
- [x] Ne pas retourner les résultats du graph avec les webacl assemblee-virtuelle/semapps#570
- [x] Gérer correctement les erreurs de permission assemblee-virtuelle/semapps#574
- [ ] install inference and test user groups defined in the defaultGraph assemblee-virtuelle/semapps#590

**Moleculer (préparation)** - _pas inclus dans le travail de Niko_
- [x] Ajouter un WebID au package sparql-endpoint assemblee-virtuelle/semapps#417
- [x] Pouvoir définir des configs pour chaque container assemblee-virtuelle/semapps#317
- [x] Pouvoir insérer des triples dans un graph assemblee-virtuelle/semapps#418
- [x] Proposer un container LDP racine assemblee-virtuelle/semapps#429
- [x] Check that all calls to triplestore have a webId (URI or anon) assemblee-virtuelle/semapps#592

**Moleculer (implémentation)**
- [x] Connaître les droits ACL d'une ressource ou d'un container assemblee-virtuelle/semapps#571
- [x] Modifier les droits ACL d'une ressource ou d'un container assemblee-virtuelle/semapps#572
- [x] Attribuer les droits à la création d'une ressource assemblee-virtuelle/semapps#573
- [x] Supprimer les droits ACL lorsqu'une ressource est supprimée assemblee-virtuelle/semapps#605
- [x] Gérer des groupes ACL assemblee-virtuelle/semapps#575
- [x] SPARQL injection. Verifier les strings qui sont inserées dans les requests SPARQL assemblee-virtuelle/semapps#620

**Estimation du temps de travail en JH**
- @nikoPLP: 10 (sans compter frontend)

**Comment by srosset81** [comment]
https://github.com/solid/web-access-control-spec

**Comment by simonLouvet** [comment]
Faire respecter des droits ACL "en dur" lors d'une requête SPARQL

**Comment by srosset81** [comment]
https://github.com/solid/web-access-control-spec

**Comment by bouviermullerp** [comment]
Seb sollicite l'aide de Nico pendant cette itération.

**Comment by GuillaumeAV** [comment]
C'est génial !!!! Félicitations @nikoPLP !!!!

**Comment by nikoPLP** [comment]
@GuillaumeAV avec plaisir !
