### ISSUE TITLE
Finaliser l'intégration des WebACL dans le code existant

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/semapps#622]
**Description**
Il y a plusieurs choses qui étaient en dehors du scope du travail de Niko, mais qui vont être nécessaires pour pouvoir déployer en prod ce travail.

**Issues liées**
- [x] Assigner des ACL par défaut sur Archipel #615
- [x] Proposer un container LDP racine #429
- [x] Configurer un groupe ACL de superadmin #610
- [x] Invalider le cache des ressources dont les droits ACL ont été modifiés #613
- [x] Mettre à jour les ressources LDP de manière plus intelligente #430
- [x] Adapter le code ActivityPub aux ACL et fixer les tests
- [x] Ne pas obliger le service LDP à dépendre du service WebACL
- [x] Merger la PR de Mathilde qui ajoute les routes via l'action addRoute
- [x] Mettre la doc du service webacl au bon endroit sur le site web
- [x] Supprimer les options obsolètes allowAnonymousEdit et allowAnonymousDelete
- [x] Dans fuseki-admin, permettre de choisir si on crée un dataset "secured" ou pas
- [x] Renommer _group en _groups

**Estimation du temps de travail en JH**
- @srosset81: 4JH (fait par moi)
- @simonLouvet:

**Comment by srosset81** [comment]
Plus que https://github.com/assemblee-virtuelle/semapps/issues/430 (que je fais la semaine prochaine) et on devrait être bon pour ce chantier :-)

**Comment by GuillaumeAV** [comment]
Hip hip hip .... :)

**Comment by srosset81** [comment]
Done :smile:

**Comment by GuillaumeAV** [comment]
Alleluia !!!!!

Le mar. 6 avr. 2021 à 10:18, Sébastien Rosset ***@***.***> a
écrit :
